Update publish-docker.yml

diff --git a/.github/workflows/publish-docker.yml b/.github/workflows/publish-docker.yml
--- a/.github/workflows/publish-docker.yml
+++ b/.github/workflows/publish-docker.yml
@@ -20,7 +20,7 @@ jobs:
         id: build
         run: |
           set -e
-          nix build -L .#dockerImage || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+          nix build -L . || echo "BUILD_FAILED=true" >> $GITHUB_ENV
 
       - name: Extract new hash from the error logs and update flake.nix
         run: |
