Update publish-docker.yml

diff --git a/.github/workflows/publish-docker.yml b/.github/workflows/publish-docker.yml
--- a/.github/workflows/publish-docker.yml
+++ b/.github/workflows/publish-docker.yml
@@ -20,7 +20,7 @@ jobs:
         id: build
         run: |
           set -e
-          nix build -L . || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+          nix build -L .#dockerImage || echo "BUILD_FAILED=true" >> $GITHUB_ENV
 
       - name: Extract new hash from the error logs and update flake.nix
         run: |
@@ -29,7 +29,7 @@ jobs:
 
             # Capture build log
             BUILD_LOG=$(mktemp)
-            nix build . > "$BUILD_LOG" 2>&1 || true
+            nix build .#dockerImage > "$BUILD_LOG" 2>&1 || true
 
             # Display build log for debugging
             echo "Build log:"
@@ -69,7 +69,7 @@ jobs:
         run: |
           if [ "$FLAKE_UPDATED" == "true" ]; then
             echo "Retrying build after flake update..."
-            nix build -L . || exit 1
+            nix build -L .#dockerImage || exit 1
           else
             echo "No flake update detected. Skipping retry."
           fi
